[EPO-3479] Add css class to handle layout fix
lsst-epo/investigation-static pull request #274
Opened 2020-09-28 18:19 UTC by georgegomez144

2020-09-28 19:10 UTC, blnkt commented
This work does not address the issue at hand. what we would like to avoid is the layout break as seen in the attached screenshot.  I'm sorry if that was unclear in the ticket description.  If it's still unclear what the desired behavior is, shoot me a message and we can talk through it together.[](url)
<img width="1197" alt="Screen Shot 2020-09-28 at 12 10 00 PM" src="https://user-images.githubusercontent.com/8166060/94475172-8e057d00-0183-11eb-9155-d389d2ccf083.png">

2020-09-28 19:11 UTC, blnkt requested changes
This work does not address the issue at hand. what we would like to avoid is the layout break as seen in the attached screenshot.  I'm sorry if that was unclear in the ticket description.  If it's still unclear what the desired behavior is, shoot me a message and we can talk through it together.[](url)
<img width="1197" alt="Screen Shot 2020-09-28 at 12 10 00 PM" src="https://user-images.githubusercontent.com/8166060/94475172-8e057d00-0183-11eb-9155-d389d2ccf083.png">

2020-09-28 19:19 UTC, georgegomez144 commented
The update keeps the widget blinker from scaling past the toolbar/header. I adapted the layout to `overflow-x: auto` in the horizontal layout to help with that.
![image](https://user-images.githubusercontent.com/8799443/94476051-cbb6d580-0184-11eb-95a6-73a52f4c1a47.png)

2020-09-29 23:32 UTC, blnkt approved these changes

2020-09-29 23:40 UTC, merged