[F] Port LinearProgress component into application
lsst-epo/investigation-static pull request #407
Opened 2021-12-30 20:42 UTC by alexgoff

For JIRA: "EPO-5669 #IN-REVIEW #comment Re-implement react-md
LinearProgress component in application"

JIRA: https://jira.lsstcorp.org/browse/<ID>

## What this change does ##

Implemented the `LinearProgress` component within the application and removed dependency on the react-md library.

## Notes for reviewers ##

Observe that the 3 areas of investigations that use linear progress components are behaving correctly, additionally check that the new component remains accessible, and check for any edge cases

- top header progress
- pages progress in menu drawer
- questions progress in menu drawer

Include an indication of how detailed a review you want on a 1-10 scale.
- 3

## Testing ##

Tested by comparing the new implementation to the previous implementation hosted on Netlify and verified the behavior and display.

## Checklist ##

If any of the following are true, please check them off
- [ ] This is a breaking change: changes in page data (`/src/data/pages/PAGE.json`) or scientific data (anything in `/static/`) and I will notify Product Marketing when it is in prod and user visible.
- [ ] This change impacts several investigations (e.g. the change affects reuseed styles, widgets, pages, QAs, utility methods, etc.)
- [x] This change is isolated to a specific page or Component (i.e. it's a one-off)
- [ ] I don't know what this change does

## Screenshots (optional) ##
### Before:
### After:

2021-12-30 20:42 UTC, alexgoff commented on src/components/site/linearProgress/index.jsx
> +const LinearProgress = ({ min, max, value, id, labelledById }) => (
close implementation of the existing `react-md` component using ARIA roles on `div` elements

2021-12-30 20:43 UTC, alexgoff commented on src/components/site/progress/index.jsx
> +          <div id="pagesBarLabel" className={headerTitle}>
added aria labels for accessibility

2022-01-05 00:04 UTC, blnkt requested changes
Looks like your changes broke the `src/site/ImageLoader` component (which is a react-md CircularProgress component)?
What is used to look like:
https://user-images.githubusercontent.com/8166060/148140129-fa921d81-2070-4aba-a077-985c63e87636.mov

what it looks like now:

https://user-images.githubusercontent.com/8166060/148140160-f18067d0-7203-4539-ae04-26515a2ba2fb.mov

2022-01-06 18:18 UTC, blnkt approved these changes

2022-01-06 18:18 UTC, merged