[F] Add Hubble plotter slider
lsst-epo/investigation-static pull request #484
Opened 2022-10-14 23:25 UTC by alexgoff

JIRA: https://jira.lsstcorp.org/browse/EPO-7067

## What this change does ##

Moves the slider component in the orbit viewer into its own component and implements it to control zoom in the Hubble plotter

## Notes for reviewers ##

This change is two minor changes, porting a component and then implementing it. An additional check should be made on top of checking out the Hubble plotter to verify that the orbit viewer slider is still functioning.

Include an indication of how detailed a review you want on a 1-10 scale.
- 5

## Testing ##

Start Expanding Universe and go forward to the `/interpreting-a-hubble-plot-2` page, test the zoom both using the slider and mouse and combinations of the two. Start Surveying the Solar System and go to `/identifying-groups-1` and verify the slider on this page is still functioning as well.

## Checklist ##

If any of the following are true, please check them off
- [ ] This is a breaking change: changes in page data (`/src/data/pages/PAGE.json`) or scientific data (anything in `/static/`) and I will notify Product Marketing when it is in prod and user visible.
- [x] This change impacts several investigations (e.g. the change affects reuseed styles, widgets, pages, QAs, utility methods, etc.)
- [x] This change is isolated to a specific page or Component (i.e. it's a one-off)
- [ ] I don't know what this change does

## Screenshots (optional) ##
### Before:
### After:

2022-10-14 23:26 UTC, alexgoff commented on src/components/site/sliderVertical/index.jsx
> +const SliderVertical = ({
moved the slider from `OrbitalViewer` playback controls into its own component

2022-10-19 22:17 UTC, alexgoff commented on src/components/charts/hubblePlot/Nudge.jsx
> +      const interval = setInterval(() => mouseDownCallback(direction), 100);
to mimic the action of holding down an arrow key, when the user's mouse is down we fire the nudging callback every 100ms then cancel it when either the mouse is released or moves outside of the button, then also reset the nudging distance.

2022-10-19 22:18 UTC, alexgoff commented on src/components/charts/hubblePlot/index.jsx
> +      showNudge: false,
`showNudge` matches `showTooltip` in most cases except that it does not display on hover.

2022-10-19 22:19 UTC, alexgoff commented on src/components/charts/hubblePlot/index.jsx
> +  resetNudge = () => {
when arrow key or mouse is released, reset the nudge distance to 1

2022-10-19 22:19 UTC, alexgoff commented on src/components/charts/hubblePlot/index.jsx
> +    const accessor =
calculate on which axes the movement will take place

2022-10-19 22:20 UTC, alexgoff commented on src/components/charts/hubblePlot/index.jsx
> +        nudgeDistance: nudgeDistance * 1.05,
increase nudge distance by 5% for the next time the method runs

2022-10-19 22:20 UTC, alexgoff commented on src/components/charts/hubblePlot/index.jsx
> +      () => {
the rest of this is copied out of the drag-n-drop code

2022-10-20 16:33 UTC, blnkt requested changes
I've spotted a couple, hopefully minor-ish, visual bugs that I think ought to be addressed before merging this work in.  Otherwise I think the implementation of the nudger is very well executed.  I especially appreciate how you handled "accelerating" the nudging on long presses.  Github isn't letting me embed my screenshots into this comment, so [I've captured my feedback in this slack message to @alexgoff instead](https://lsstc.slack.com/archives/D02NY0C5NE6/p1666284185355819).

2022-10-20 21:06 UTC, alexgoff commented on src/components/charts/hubblePlot/Nudge.jsx
> +  const setEventHandlers = () => {
onFocus, keydown and keyup event handlers are set on the nudger so that use of keyboard arrow keys is not disrupted

2022-10-20 21:06 UTC, alexgoff commented on src/components/charts/hubblePlot/Nudge.jsx
> +  const removeEventHandlers = () => {
onBlur, the event handlers are removed so that the event handlers for the data points can resume

2022-10-20 21:07 UTC, alexgoff commented on src/components/charts/hubblePlot/Nudge.jsx
> +    <foreignObject {...{ x, y, width }} height={width}>
wrap inside a foreignObject, this component is now scaled to the SVG and can simply reuse the x/y from the point selected

2022-10-20 21:08 UTC, alexgoff commented on src/components/charts/hubblePlot/index.jsx
> +        const isHtmlClick = d3Event.path.some(
check to see if this click bubble up from a `foreignObject`, if so it should be ignored.

2022-10-26 23:01 UTC, merged